// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvfhvteikbqswrgblili.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2Zmh2dGVpa2Jxc3dyZ2JsaWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTU0ODUsImV4cCI6MjA2OTAzMTQ4NX0.G7hPU1g5xijGJdgXSx9WbxxSXrde5qBGDYW6umvppGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});